
archetypeDir           = "archetypes"
author                 = "admin"
baseUrl                = "http://omarsmak.github.io"
buildDrafts            = false
relativeURLs           = true
canonifyUrls           = true
contentDir             = "content"
languageCode           = "en-us"
layoutDir              = "layouts"
publishDir             = "public"
theme                  = "pixyll-custom"
title                  = "Omar Al-Safi"
enableEmoji            = true

[indexes]
  category = "categories"
  tag = "tags"

[params]
  twitter_username = "omarsmak"  
  github_username = "omarsmak"
  linkedin_username = "omar-al-safi-b7891745"
  custom_css = ["css/custom.css"]
  intro = "Software Engineer at Talend and Apache Camel PMC"